services:
  bind-server:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind-server
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/db.cdn.test:/etc/bind/db.cdn.test
      - ./bind/db.127:/etc/bind/db.127
    environment:
      - BIND9_LOG_LEVEL=info
    networks:
      - cdn-network
    entrypoint: [ "/usr/sbin/named", "-f", "-c", "/etc/bind/named.conf" ]

  load-balancer-1:
    image: nginx:latest
    container_name: load-balancer-1
    ports:
      - "8081:80"  # Port forwarding for the first load balancer
    volumes:
      - ./lb1/default.conf:/etc/nginx/nginx.conf  # Configuration for Round Robin load balancing
    depends_on:
      - bind-server
      - node1
      - node2
    networks:
      - cdn-network

  load-balancer-2:
    image: nginx:latest
    container_name: load-balancer-2
    ports:
      - "8082:80"  # Port forwarding for the second load balancer
    volumes:
      - ./lb2/default.conf:/etc/nginx/nginx.conf  # Configuration for Weighted Round Robin load balancing
    depends_on:
      - bind-server
      - node3
      - node4
    networks:
      - cdn-network

  node1:
    build:
      context: ./nodes/node1
    container_name: node1
    ports:
      - "8083:80"
    networks:
      - cdn-network

  node2:
    build:
      context: ./nodes/node2
    container_name: node2
    ports:
      - "8084:80"
    networks:
      - cdn-network

  node3:
    build:
      context: ./nodes/node3
    container_name: node3
    ports:
      - "8085:80"
    networks:
      - cdn-network

  node4:
    build:
      context: ./nodes/node4
    container_name: node4
    ports:
      - "8086:80"
    networks:
      - cdn-network

networks:
  cdn-network:
    driver: bridge